# Form implementation generated from reading ui file 'save_elements_form.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 153)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.element_type = QtWidgets.QLineEdit(self.centralwidget)
        self.element_type.setGeometry(QtCore.QRect(50, 40, 471, 20))
        self.element_type.setObjectName("element_type")
        self.element_name = QtWidgets.QLineEdit(self.centralwidget)
        self.element_name.setGeometry(QtCore.QRect(50, 70, 471, 20))
        self.element_name.setObjectName("element_name")
        self.save_element = QtWidgets.QPushButton(self.centralwidget)
        self.save_element.setGeometry(QtCore.QRect(50, 100, 471, 23))
        self.save_element.setObjectName("save_element")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.element_type.setPlaceholderText(_translate("MainWindow", "Тип элемента"))
        self.element_name.setPlaceholderText(_translate("MainWindow", "Наименование элемента"))
        self.save_element.setText(_translate("MainWindow", "Сохранить элемент"))
